<?php

namespace Dowdow\LeagueOfLegendsAPIBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamMemberInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamMemberInfoRepository extends EntityRepository
{
}
